### ISSUE TITLE
docker-compose 部署成功，可以进入后端，但无法上传文件，报错

### ISSUE THREAD

**Issue by geekidentity** [mnt-ltd/moredoc#52]
MySQL 是已经安装好的，docker-compose 配置
```yaml
networks:
  moredoc-network:
    # driver: bridge
    external: false

services:
  moredoc-elasticsearch:
    build:
      context: .
      dockerfile: es-dockerfile
    container_name: moredoc-elasticsearch
    environment:
      - discovery.type=single-node
      # ES 内存限制
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - /app/moredoc/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - moredoc-network
  moredoc-server:
    build:
      context: .
      dockerfile: dockerfile
    container_name: moredoc-server
    environment:
      - MOREDOC_DATABASE_DSN=username:password@tcp(192.168.31.120:3306)/moredoc?charset=utf8mb4&loc=Local&parseTime=true
      # 【改】请务必更换为自己的JWT_SECRET，建议使用随机字符串
      - MOREDOC_JWT_SECRET="random"
      # 对象存储。默认为本地存储。如需
      # - MOREDOC_CLOUD_STORE_STORE_TYPE=local
      # - MOREDOC_CLOUD_STORE_DOMAIN=
      # - MOREDOC_CLOUD_STORE_BUCKET=
      # - MOREDOC_CLOUD_STORE_ACCESS_KEY=
      # - MOREDOC_CLOUD_STORE_SECRET_KEY=
      # - MOREDOC_CLOUD_STORE_ENDPOINT=
    networks:
      - moredoc-network
    ports:
      - "8880:8880"
    volumes:
      - ./server/:/home/moredoc
    restart: always
```

上传文档时报错

![Image](https://github.com/user-attachments/assets/691c542b-b101-426c-bfdb-f69ca47abbf4)

日志如下

```
2025-02-06T07:10:15.610Z	error	model	model/articleRelate.go:256	GetRelatedArticles	{"error": "mkdir indexes: permission denied"}
moredoc/model.(*DBModel).GetRelatedArticlesByFulltextSearch
	/Users/truthhun/workspace/git.mnt.ltd/moredoc/model/articleRelate.go:256
moredoc/biz.(*ArticleAPIService).GetRelatedArticles
	/Users/truthhun/workspace/git.mnt.ltd/moredoc/biz/article.go:502
moredoc/api/v1._ArticleAPI_GetRelatedArticles_Handler.func1
	/Users/truthhun/workspace/git.mnt.ltd/moredoc/api/v1/article.pb.go:1563
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1
	/Users/truthhun/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/recovery/interceptors.go:33
moredoc/service.Run.ChainUnaryServer.func5.1.1
	/Users/truthhun/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
moredoc/service.Run.(*Auth).AuthUnaryServerInterceptor.func4
	/Users/truthhun/workspace/git.mnt.ltd/moredoc/middleware/auth/auth.go:50
moredoc/service.Run.ChainUnaryServer.func5.1.1
	/Users/truthhun/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
moredoc/service.Run.ChainUnaryServer.func5
	/Users/truthhun/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34
moredoc/api/v1._ArticleAPI_GetRelatedArticles_Handler
	/Users/truthhun/workspace/git.mnt.ltd/moredoc/api/v1/article.pb.go:1565
google.golang.org/grpc.(*Server).processUnaryRPC
	/Users/truthhun/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1282
google.golang.org/grpc.(*Server).handleStream
	/Users/truthhun/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1616
google.golang.org/grpc.(*Server).serveStreams.func1.2
	/Users/truthhun/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:921
2025-02-06T07:15:03.373Z	error	AttachmentAPIService	biz/attachment.go:463	SaveUploadedFile	{"error": "open cache/uploads/2025/02/06/15aeb3ce-e45a-11ef-b316-0242ac1f0003.pdf: no such file or directory", "filename": "高质量C++C 编程指南.pdf", "cachePath": "cache/uploads/2025/02/06/15aeb3ce-e45a-11ef-b316-0242ac1f0003.pdf"}
moredoc/biz.(*AttachmentAPIService).saveFile
	/Users/truthhun/workspace/git.mnt.ltd/moredoc/biz/attachment.go:463
moredoc/biz.(*AttachmentAPIService).UploadDocument
	/Users/truthhun/workspace/git.mnt.ltd/moredoc/biz/attachment.go:221
github.com/gin-gonic/gin.(*Context).Next
	/Users/truthhun/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173
moredoc/service/serve.RegisterGinRouter.(*Auth).AuthGin.func2
	/Users/truthhun/workspace/git.mnt.ltd/moredoc/middleware/auth/auth.go:88
github.com/gin-gonic/gin.(*Context).Next
	/Users/truthhun/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173
moredoc/model.(*DBModel).SSRMidleware
	/Users/truthhun/workspace/git.mnt.ltd/moredoc/model/util.go:989
github.com/gin-gonic/gin.(*Context).Next
	/Users/truthhun/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/Users/truthhun/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/recovery.go:101
github.com/gin-gonic/gin.(*Context).Next
	/Users/truthhun/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173
github.com/gin-contrib/gzip.(*gzipHandler).Handle
	/Users/truthhun/go/pkg/mod/github.com/gin-contrib/gzip@v0.0.5/handler.go:60
github.com/gin-gonic/gin.(*Context).Next
	/Users/truthhun/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/Users/truthhun/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/gin.go:616
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/Users/truthhun/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/gin.go:572
net/http.serverHandler.ServeHTTP
	/opt/homebrew/Cellar/go/1.21.6/libexec/src/net/http/server.go:2938
net/http.(*conn).serve
	/opt/homebrew/Cellar/go/1.21.6/libexec/src/net/http/server.go:2009
```
